### ISSUE TITLE
Restore Cluster from gcp bucket

### ISSUE THREAD

**Issue by mabombo** [zalando/postgres-operator#717] opened 2019-11-13 08:44 UTC
I have followed the instructions posted on this blog
**Running PostgreSQL in Google Kubernetes Engine**
**https://www.redpill-linpro.com/techblog/2019/09/28/postgres-in-kubernetes.html**

Using GCP and Bucket to store backups it works well.
The kubernetes cluster was created using gcp.

The problem is when i try to restore the entire cluster using PITR from backups present on the bucket.

The restore yaml is the follow

apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-minimal-cluster
  namespace: default
spec:
  teamId: "ACID"
  volume:
    size: 1Gi
  numberOfInstances: 2
  postgresql:
    version: "11"
  clone:
    uid: "341f6c79-05e8-11ea-a030-42010aac0078"
    name: acid-minimal-cluster
    timestamp: "2019-11-13T17:23:00+02:00"

So the first node goes up without wal restoring, **acid-minimal-cluster-0**, the replica **acid-minimal-cluster-1** doesn't start with the follow error:

2019-11-13 08:22:10,713 **CRITICAL: system ID mismatch, node acid-minimal-cluster-1 belongs to a different cluster: 6758699063451381825 != 6758691900714311745**
2019-11-13 08:22:11,198 INFO: Lock owner: acid-minimal-cluster-0; I am acid-minimal-cluster-1
2019-11-13 08:22:11,291 INFO success: patroni entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-11-13 08:22:12,293 INFO exited: patroni (exit status 1; not expected)
2019-11-13 08:22:13,296 INFO spawned: 'patroni' with pid 3075
2019-11-13 08:22:13,723 INFO: No PostgreSQL configura

I'm using the last operator image

The change i have made are the same reported on the blog
**https://www.redpill-linpro.com/techblog/2019/09/28/postgres-in-kubernetes.html**

What's wrong?
let my know if you need more information.
Thanks for your help

**Comment by FxKu** [comment] 2019-11-15 15:19
Haven't see the error so far, but I think it's because your cloned cluster is called the same as your source cluster. If one instance starts restoring wal segments from the bucket, sounds like it should work, in general.

**Comment by FxKu** [comment] 2019-11-20 13:09
@mabombo is it working for you when using another name for the new cluster?

**Comment by mabombo** [comment] 2019-11-20 13:21
No i have the same problem also if i change the cluster name

**Comment by FxKu** [comment] 2019-11-25 12:18
@mabombo in the meantime I've also came across this error message. It's related to Patroni bootstrapping new clusters. Please visit, the [issues](https://github.com/zalando/patroni/issues?utf8=%E2%9C%93&q=is%3Aissue+%22system+ID+mismatch%22) section, to hopefully find further assistance.

**Comment by FxKu** [comment] 2019-12-20 11:12
Closing for now. Mentioned the cause to this error. Feel free to reopen anytime.

**Closed by FxKu** 2019-12-20 11:12 UTC
