### ISSUE TITLE
Compatibility with Kubernetes v1.29

### ISSUE THREAD

**Issue by toabi** [zalando/postgres-operator#2603] opened 2024-04-11 03:58 UTC
The [table in the readme](https://github.com/zalando/postgres-operator?tab=readme-ov-file#supported-postgres--k8s-versions) currently only lists v1.28 as max version.

Is there really anything blocking the use of the operator in a kubernetes 1.29 cluster?

**Comment by FxKu** [comment] 2024-04-15 09:26
![image](https://github.com/zalando/postgres-operator/assets/5940260/0475fc64-0e11-4765-ad76-1b06d153a19c)

I have only noticed one [incompatibility](https://github.com/zalando/postgres-operator/blob/master/pkg/cluster/k8sres.go#L1859) when changing libraries to 1.29. But it's only the go-client. Would be happy if you can test out operator on 1.29. We are just moving to 1.28 here.

**Comment by minimax75** [comment] 2024-04-19 09:48
Hi FxKu,
I ran an update from EKS 1.28 to 1.29 on our test-box and observed following problem.
Leader-Pods are not evicted automatically from a cordoned and draining node. I need to manually switchover and then the pod gets evicted.
I did not observe this behavior during the upgrade from 1.27 to 1.28.

**Comment by FxKu** [comment] 2024-04-23 12:59
@minimax75 sounds unrelated to 1.29. Maybe you're using a newer Spilo/Patroni version? I would update to 1.11 to be sure you include this fix: https://github.com/zalando/postgres-operator/pull/2515

**Comment by 98jan** [comment] 2024-04-23 16:13
installed today in my kubeadm provisioned Kubernetes Cluster with version 1.29.0 and everything was working as expected for my use case.

**Comment by minimax75** [comment] 2024-04-24 07:41
updated to 1.11 and the issue is gone, so looks like it is related to spilo-15 3.2-p1 and operator 1.10.1

**Comment by FxKu** [comment] 2024-06-14 10:02
I have updated the README. You can run the operator on K8s 1.29 and higher without any problems.

**Closed by FxKu** 2024-06-14 10:02 UTC
Labels: question
