### ISSUE TITLE
Support removing CPU limit

### ISSUE THREAD

**Issue by josedev-union** [zalando/postgres-operator#2428] opened 2023-09-20 13:34 UTC
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** e.g. registry.opensource.zalan.do/acid/postgres-operator:v1.9.0
- **Where do you run it - cloud or metal? GKE
- **Are you running Postgres Operator in production?** [yes]
- **Type of issue?** [feature request]

## Context
I've been running zalando postgresql clusters as the database for [Graph node](https://github.com/graphprotocol/graph-node) for several months. I collected postgres metrics(from postgres-exporter deployed as a sidecar of postgresql cluster) and patroni metrics also from spilo 8008 port to found the RC of the frequent performance issues (facing when I ran compute-intensive queries in subgraph).
After some investigation, I figured out the reason and it was cpu throttling in postgresql clusters. To make things worse, becaues of slowness by cpu throttling, db connections are increased by graph-node. The increase in the active connection results in the resource usage increase. Cyclic causality

Cpu throttling occurs even if postgres pods don't use much cpu in fact and it turns out k8s cpu limit is ridiculous. I want to stop using cpu limit but when i set it as none, default value `1` is used.

## Expectation
If cpu limit field is set as `null` explicitly, I expect to not set cpu limit to postgresql pods instead of setting default values.
If cpu limit field is not set explicitly, I expect the default limit value.

**Comment by jchomat** [comment] 2023-11-27 10:34
Hello,
CPU throttling is pretty annoying.
i would prefered disabled it if not set but at least having a possibility to disable it if needed could be great

**Comment by andreykeen** [comment] 2023-11-30 18:37
The same thoughts about CPU throttling. I'd prefer to be able to disable any settings in `postgres_pod_resources` section.

**Comment by oldluke92** [comment] 2024-01-08 09:00
This is a duplicate of #2057, which is also open.

**Comment by mmoscher** [comment] 2024-02-14 21:59
@josedev-union this issue has been solved with #2425 and can be closed.

**Closed** 2024-02-15 09:54 UTC
